<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CoaSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['code' => '1', 'name' => 'Kas', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '11', 'name' => 'Kas Apotek', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '111', 'name' => 'Kas Tunai Apotek', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1111', 'name' => 'Kas kasir 1', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1112', 'name' => 'Kas kasir 2', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '112', 'name' => 'Kas Bank Apotek', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1121', 'name' => 'Kas Digital', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '12', 'name' => 'Piutang', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '121', 'name' => 'Piutang Asuransi BPJS', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '122', 'name' => 'Piutang Antar Unit', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '123', 'name' => 'Cadangan Kerugian Piutang', 'type' => 'Asset', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '13', 'name' => 'Uang Muka & Biaya dibayar di Muka', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '131', 'name' => 'Uang Muka Pembelian Barang', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '132', 'name' => 'Uang Muka Pembelian Aset', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '133', 'name' => 'Uang Muka Lainnya', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '134', 'name' => 'Biaya Dibayar di Muka', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1341', 'name' => 'Sewa Dibayar di Muka', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1342', 'name' => 'Asuransi Dibayar di Muka', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1343', 'name' => 'Langganan Dibayar di Muka', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1344', 'name' => 'Biaya Dibayar di Muka Lainnya', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '14', 'name' => 'Persediaan', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '141', 'name' => 'Persediaan Obat', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1411', 'name' => 'Gitria Derma', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1412', 'name' => 'Obat Resep', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1413', 'name' => 'Obat Bebas Terbatas', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1414', 'name' => 'Obat Bebas', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1415', 'name' => 'Obat Generic', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1416', 'name' => 'Obat Bermerek', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1417', 'name' => 'Obat Narkotika', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1418', 'name' => 'Obat Psikotropika', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1419', 'name' => 'Obat Prekursor', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '14110', 'name' => 'Obat Program/Khusus', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '14111', 'name' => 'Obat Keras', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '142', 'name' => 'Persediaan Alat Kesehatan', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1421', 'name' => 'Alkes Habis Pakai', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1422', 'name' => 'Alkes Diagnostik', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1423', 'name' => 'Alkes Non Medis', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1424', 'name' => 'APD', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1425', 'name' => 'Perlengkapan Medis', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '143', 'name' => 'Persediaan Kosmetic & Personal Care', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1431', 'name' => 'Kosmetik Wajah', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1432', 'name' => 'Kosmetik Tubuh', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1433', 'name' => 'Perawatan Rambut', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1434', 'name' => 'Perawatan Mulut', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1435', 'name' => 'Personal Care Lainnya', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '144', 'name' => 'Persediaan Drug Store', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1441', 'name' => 'Susu', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1442', 'name' => 'Makanan & Minuman', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1443', 'name' => 'Vitamin & Minuman Kesehatan', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1444', 'name' => 'Perlengkapan Bayi', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1445', 'name' => 'Perlengkapan Rumah Tangga', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1446', 'name' => 'ATK & Aksesori', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1447', 'name' => 'Lain-lain', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '145', 'name' => 'Persediaan Herbal & Suplemen', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1451', 'name' => 'Herbal', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1452', 'name' => 'Suplemen', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1453', 'name' => 'Vitamin', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1454', 'name' => 'Produk Nutrisi', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '146', 'name' => 'Persediaan Konsinyasi', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1461', 'name' => 'Obat Konsinyasi', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1462', 'name' => 'Alkes Konsinyasi', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '1463', 'name' => 'Kosmetik Konsinyasi', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '147', 'name' => 'Persediaan Dalam Perjalanan', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '148', 'name' => 'Persediaan Barang Rusak', 'type' => 'Asset', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '149', 'name' => 'Cadangan Penurunan Nilai Persediaan', 'type' => 'Asset', 'normal_balance' => 'credit', 'balance' => 0],

            ['code' => '2', 'name' => 'Liabilitas', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '21', 'name' => 'Utang Supplier & Vendor', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '211', 'name' => 'Utang Dagang', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '212', 'name' => 'Utang Vendor Jasa', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '22', 'name' => 'Utang Operasional', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '221', 'name' => 'Utang Utilitas', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '222', 'name' => 'Utang Pajak', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '223', 'name' => 'Utang BPJS', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '224', 'name' => 'Utang Sewa', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '225', 'name' => 'Utang Lainnya', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '23', 'name' => 'Utang SDM', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '231', 'name' => 'Utang Gaji', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '232', 'name' => 'Utang THR', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '233', 'name' => 'Utang Bonus', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '24', 'name' => 'Utang Tenaga Medis', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '241', 'name' => 'Utang Fee Dokter', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '242', 'name' => 'Utang Jasa Karyawan', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '25', 'name' => 'Hutang Bank', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '26', 'name' => 'Hutang Internal', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '27', 'name' => 'Pendapatan Diterima Dimuka', 'type' => 'Liability', 'normal_balance' => 'credit', 'balance' => 0],
            
            ['code' => '3', 'name' => 'Modal/Prive/Ekuitas', 'type' => 'Equity', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '31', 'name' => 'Modal Saham', 'type' => 'Equity', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '311', 'name' => 'Modal Disetor', 'type' => 'Equity', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '312', 'name' => 'Tambahan Modal Disetor', 'type' => 'Equity', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '32', 'name' => 'Saldo Laba', 'type' => 'Equity', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '321', 'name' => 'Laba Tahun Berjalan', 'type' => 'Equity', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '322', 'name' => 'Laba Ditahan', 'type' => 'Equity', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '33', 'name' => 'Cadangan', 'type' => 'Equity', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '331', 'name' => 'Cadangan Umum', 'type' => 'Equity', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '332', 'name' => 'Cadangan Investasi', 'type' => 'Equity', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '34', 'name' => 'Dividen', 'type' => 'Equity', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '341', 'name' => 'Dividen Belum Dibayar', 'type' => 'Equity', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '342', 'name' => 'Dividen Dibayarkan', 'type' => 'Equity', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '35', 'name' => 'Prive', 'type' => 'Equity', 'normal_balance' => 'debit', 'balance' => 0],

            ['code' => '4', 'name' => 'Pendapatan', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '41', 'name' => 'Penjualan', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '411', 'name' => 'Obat Resep', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '412', 'name' => 'Obat Bebas', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '413', 'name' => 'Obat', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '414', 'name' => 'OTC', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '415', 'name' => 'BMHP', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '416', 'name' => 'Alkes', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '417', 'name' => 'Kosmetik', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '418', 'name' => 'Suplemen', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '419', 'name' => 'Konsul Online', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '42', 'name' => 'Pendapatan Jasa', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '421', 'name' => 'Administrasi', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '422', 'name' => 'Konseling Farmasi', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '423', 'name' => 'Penunjang', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '424', 'name' => 'Dokter', 'type' => 'Revenue', 'normal_balance' => 'credit', 'balance' => 0],
            ['code' => '43', 'name' => 'Pengurang Pendapatan', 'type' => 'Revenue', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '431', 'name' => 'Diskon', 'type' => 'Revenue', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '432', 'name' => 'Retur', 'type' => 'Revenue', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '434', 'name' => 'Promo', 'type' => 'Revenue', 'normal_balance' => 'debit', 'balance' => 0],

            ['code' => '5', 'name' => 'Beban', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '51', 'name' => 'Harga Pokok Penjualan', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '511', 'name' => 'HPP Obat', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '512', 'name' => 'HPP Alat Kesehatan', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '513', 'name' => 'HPP BMHP', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '514', 'name' => 'HPP Kosmetik', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '515', 'name' => 'HPP Suplemen', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '52', 'name' => 'Beban Pajak', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '521', 'name' => 'PPh', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '522', 'name' => 'Pajak Daerah', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '523', 'name' => 'Pajak Lainnya', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '53', 'name' => 'Beban Personel', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '531', 'name' => 'Gaji Personel', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '532', 'name' => 'THR', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '533', 'name' => 'Bonus/Insentif', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '534', 'name' => 'Fee Dokter', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '535', 'name' => 'Fee Karyawan', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '536', 'name' => 'BPJS Kesehatan', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '537', 'name' => 'BPJS Ketenagakerjaan', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '538', 'name' => 'Tunjangan', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '54', 'name' => 'Beban Operasional', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '541', 'name' => 'Listrik', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '542', 'name' => 'Air', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '543', 'name' => 'Internet & Telepon', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '544', 'name' => 'ATK', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '545', 'name' => 'Kebersihan', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '546', 'name' => 'Keamanan', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '547', 'name' => 'Perawatan & Servis Peralatan', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '548', 'name' => 'Transportasi', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '549', 'name' => 'Konsumsi Operasional', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '55', 'name' => 'Beban Administrasi & Umum', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '551', 'name' => 'Administrasi Bank', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '552', 'name' => 'Materai', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '553', 'name' => 'Perizinan', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '554', 'name' => 'Iuran Organiasi', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '555', 'name' => 'Langganan Software/SIM Apotek', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '556', 'name' => 'Penyusutan Aset Tetap', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '557', 'name' => 'Amortisasi', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '559', 'name' => 'Bunga Pinjaman', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '56', 'name' => 'Beban Pemasaran', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '561', 'name' => 'Promosi', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '562', 'name' => 'Iklan', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '563', 'name' => 'Diskon Promosi', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '564', 'name' => 'Sponsorship', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '565', 'name' => 'Media Sosial/Content Creator', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '57', 'name' => 'Beban Lainnya', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '571', 'name' => 'Beban Obat Expired', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '572', 'name' => 'Beban Obat Rusak', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '573', 'name' => 'Selisih Stok Opname', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '574', 'name' => 'Beban Pemusnahan Obat', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '575', 'name' => 'Piutang Tak Tertagih', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '576', 'name' => 'Denda & Penalti', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '577', 'name' => 'Beban Lain-lain', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
            ['code' => '578', 'name' => 'Beban fasilitas bersama', 'type' => 'Expense', 'normal_balance' => 'debit', 'balance' => 0],
        ];

        // Ensure accounts table is truncated first if we are doing fresh seed
        $this->db->query('SET FOREIGN_KEY_CHECKS = 0');
        $this->db->table('accounts')->truncate();
        $this->db->query('SET FOREIGN_KEY_CHECKS = 1');
        
        foreach ($data as $row) {
            // Type logic based on Code string if not properly specified above
            // But they are already mapped appropriately to Asset, Liability, Equity, Revenue, Expense.
            
            $this->db->table('accounts')->insert($row);
        }
    }
}
